"use client";

import Link from "next/link";
import { useState } from "react";
import { ProHeader } from "./professional-portal";

export function AssessmentRunner({ account, salonName, client, assessmentId, definition }) {
  const [step, setStep] = useState(0); const [answers, setAnswers] = useState({}); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const question = definition.questions[step]; const answered = Boolean(answers[question.id]); const isLast = step === definition.questions.length - 1;
  async function proceed() { if (!answered) return; if (!isLast) { setStep(step + 1); return; } setBusy(true); setError(""); const response = await fetch(`/api/professional/clients/${client.id}/assessments/${assessmentId}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ answers }) }); const data = await response.json(); if (!response.ok) { setError(data.error); setBusy(false); return; } window.location.assign(`/professional/clients/${client.id}`); }
  return <main className="professional-portal"><ProHeader account={account} salonName={salonName} /><section className="pro-container assessment-runner"><Link className="pro-back" href={`/professional/clients/${client.id}`}>‹ Înapoi la fișa clientului</Link><p className="pro-label">Protocol clinic · {String(step + 1).padStart(2, "0")} / {String(definition.questions.length).padStart(2, "0")}</p><h1>{definition.title}</h1><p className="assessment-client">Evaluare pentru <strong>{client.name}</strong></p><div className="assessment-progress"><i style={{ width: `${((step + 1) / definition.questions.length) * 100}%` }} /></div><article className="assessment-card"><p className="assessment-section">{question.section || "Observație profesională"}</p><h2>{question.label}</h2>{question.options ? <div className="assessment-options">{question.options.map((option) => <button key={option.value} className={answers[question.id] === option.value ? "is-selected" : ""} onClick={() => setAnswers({ ...answers, [question.id]: option.value })}>{option.label}<span>{answers[question.id] === option.value ? "✓" : ""}</span></button>)}</div> : <textarea value={answers[question.id] || ""} onChange={(event) => setAnswers({ ...answers, [question.id]: event.target.value })} placeholder="Consemnează observația" />}{error && <p className="form-error">{error}</p>}<div className="assessment-actions">{step > 0 && <button className="pro-ghost" onClick={() => setStep(step - 1)}>Înapoi</button>}<button className="pro-primary" disabled={!answered || busy} onClick={proceed}>{busy ? "Se salvează..." : isLast ? "Salvează evaluarea" : "Continuă"}</button></div></article></section></main>;
}
