"use client";

import Link from "next/link";
import { useState } from "react";
import { LogoutButton } from "./logout-button";

function Mark() { return <span className="pro-mark" aria-hidden="true">✦</span>; }

export function ProHeader({ account, salonName }) {
  return <header className="pro-header"><Link href="/professional" className="pro-brand"><Mark /> <span>Insight<span>Beauty</span></span></Link><div className="pro-account"><span>{salonName || "Portofoliu individual"}</span><strong>{account.name}</strong><LogoutButton /></div></header>;
}

function Phenotype({ code }) {
  if (!code) return null;
  const colors = ["#b87b82", "#c9a27b", "#8da394", "#859ca6"];
  return <span className="phenotype" aria-label={`Fenotip Baumann ${code}`}>{code.split("").map((letter, index) => <i key={`${letter}-${index}`} style={{ backgroundColor: colors[index] }}>{letter}</i>)}</span>;
}

export function NewClientModal({ onClose, onCreate, pending, error, invitation }) {
  return <div className="pro-modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="new-client-title"><form className="pro-modal" onSubmit={onCreate}><div className="pro-modal-heading"><div><p className="pro-label">Dosar nou</p><h2 id="new-client-title">Clientă nouă</h2></div><button type="button" className="pro-close" onClick={onClose} aria-label="Închide">×</button></div><p>Trimite o invitație securizată. Clienta acceptă GDPR și își completează evaluarea înainte ca dosarul să devină activ.</p><label>Nume complet<input name="name" placeholder="Ex. Maria Popescu" required /></label><label>Email<input name="email" type="email" placeholder="maria@email.ro" required /></label><label>Telefon <small>opțional</small><input name="phone" type="tel" placeholder="07xx xxx xxx" /></label>{error && <p className="form-error">{error}</p>}{invitation && <label className="pro-invitation">Invitația este pregătită<input value={invitation} readOnly onFocus={(event) => event.target.select()} /></label>}<div className="pro-modal-actions"><button type="button" className="pro-ghost" onClick={onClose}>Anulează</button><button className="pro-primary" disabled={pending}>{pending ? "Se creează..." : "Creează invitația"}</button></div></form></div>;
}

export function ProfessionalPortal({ account, salonName, clients }) {
  const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [invitation, setInvitation] = useState("");
  async function createClient(event) { event.preventDefault(); setPending(true); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/professional/clients", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const body = await response.json(); if (!response.ok) { setError(body.error); setPending(false); return; } setInvitation(`${window.location.origin}${body.onboardingUrl}`); setPending(false); }
  return <main className="professional-portal"><ProHeader account={account} salonName={salonName} /><section className="pro-container"><div className="pro-dashboard-heading"><div><h1>Clientele tale</h1><p>{clients.length} fișe în portofoliu</p></div><button className="pro-primary pro-add" onClick={() => { setOpen(true); setError(""); setInvitation(""); }}><span>＋</span> Clientă nouă</button></div><div className="pro-client-grid">{clients.map((client) => <Link key={client.id} href={`/professional/clients/${client.id}`} className="pro-client-card"><div><h2>{client.name}</h2><p>{client.visitCount} vizite · ultima {client.lastVisit || "—"}</p></div><div className="pro-card-end">{client.baumannType ? <Phenotype code={client.baumannType} /> : <span className="pro-pending">În așteptare</span>}<span className="pro-chevron">›</span></div></Link>)}</div>{!clients.length && <div className="pro-empty">Nicio clientă încă. Creează prima invitație pentru a începe un dosar.</div>}</section>{open && <NewClientModal onClose={() => setOpen(false)} onCreate={createClient} pending={pending} error={error} invitation={invitation} />}</main>;
}

export function ProfessionalDossier({ account, salonName, client, visits, questionnaireHistory, testCatalog, children }) {
  const [tab, setTab] = useState("general");
  const initialBaumann = questionnaireHistory.find((item) => item.id === "baumann");
  const completed = new Set(questionnaireHistory.map((item) => item.id));
  const nextTest = testCatalog.find((test) => !completed.has(test.id));
  return <main className="professional-portal"><ProHeader account={account} salonName={salonName} /><section className="pro-container pro-dossier"><Link className="pro-back" href="/professional">‹ Toate clientele</Link><div className="pro-dossier-heading"><div><h1>{client.name}</h1><p>{client.email}{client.phone ? ` · ${client.phone}` : ""} · {visits.length} vizite</p></div>{client.baumannType && <div className="pro-phenotype-wrap"><span>Fenotip Baumann</span><Phenotype code={client.baumannType} /></div>}</div><div className="pro-tabs">{[["general", "Date generale"], ["tests", "Teste & analize"], ["visits", "Istoric vizite"]].map(([id, label]) => <button key={id} className={tab === id ? "is-active" : ""} onClick={() => setTab(id)}>{label}</button>)}</div>{tab === "general" && <div className="pro-info-grid"><article><span>Stare dosar</span><h3>{client.onboardingStatus === "completed" ? "Activ și consimțit" : "În așteptarea onboardingului"}</h3><p>{client.onboardingStatus === "completed" ? "Clienta a confirmat consimțământul GDPR și poate primi recomandări în dosarul personal." : "Invitația a fost creată, dar clienta nu a finalizat încă acordul și evaluarea."}</p></article><article><span>Primul obiectiv</span><h3>De completat la consult</h3><p>Consemnează motivul prezentării și contextul relevant la prima vizită.</p></article></div>}{tab === "tests" && <div className="pro-tab-card"><div><p className="pro-label">Protocol de evaluare</p><h2>Teste & analize</h2><p>Instrumentele sunt păstrate în succesiunea clinică stabilită. Un test devine disponibil doar după finalizarea celui anterior.</p></div>{initialBaumann && <div className="pro-test-result"><span>Baumann</span><Phenotype code={client.baumannType} /></div>}<ol className="pro-test-sequence">{testCatalog.map((test) => { const done = completed.has(test.id); const current = nextTest?.id === test.id; return <li className={done ? "is-done" : current ? "is-current" : ""} key={test.id}><span>{String(test.sequence).padStart(2, "0")}</span><div><strong>{test.name}</strong><small>{test.group} · {test.description}</small></div><em>{done ? "Finalizat" : current ? "Următorul" : "În așteptare"}</em></li>; })}</ol><div className="pro-visit-slot">{children}</div></div>}{tab === "visits" && <div className="pro-visits">{visits.length ? visits.map((visit) => <article key={visit.id}><div><span>{visit.date}</span><h3>{visit.procedures.length ? visit.procedures.join(" · ") : "Consultație și evaluare"}</h3></div><p>{visit.notes || "Fără observații clinice."}</p>{visit.treatments.length > 0 && <small>Tratament: {visit.treatments.join(", ")}</small>}</article>) : <div className="pro-empty">Nicio vizită înregistrată încă.</div>}</div>}</section></main>;
}
